### ISSUE TITLE
UG: Explain how to run the JAR file on a Mac

### ISSUE THREAD

**Issue by damithc** [se-edu/addressbook-level3#140]
Current UG:
![image](https://user-images.githubusercontent.com/1673303/179824067-210b95d4-c92f-4017-a4e6-993f96220af3.png)

Suggestion: Perhaps add a note for Mac users on how to run the JAR file (as simple double-clicking might not work)?

**Comment by Eclipse-Dominator** [comment]
Currently, the documentation is generalized for usage via command line like so:

![image](https://github.com/se-edu/addressbook-level3/assets/4567895/2c1b4332-e617-414f-9414-aaa54624aab4)

I am thinking of reverting back to double click but include an alternative to opening the jar file via cli like so:

![image](https://github.com/se-edu/addressbook-level3/assets/4567895/ea4f69e1-e8af-4bed-a95c-83788b243309)

and since opening via cli is a generalised approach, I dont specifically see the need to reference Mac Users for this case.

**Comment by Eclipse-Dominator** [comment]
Think this is a duplicate of #62

**Comment by damithc** [comment]
Yes, now we require users to use the CLI. Let's keep it like that so that it is easier to ensure the app is run using the correct version of Java when run using the CLI.
