### ISSUE TITLE
Checkstyle guide: CODESTYLE.OFF or CODESTYLE.OFF?

### ISSUE THREAD

**Issue by damithc** [se-edu/addressbook-level3#154]
Not directly related to AB3, but can someone investigate https://github.com/nus-cs2103-AY2223S2/forum/issues/77 to see if the guide needs to be updated?

**Comment by damithc** [comment]
@se-edu/tech-team-level1 Any help with this?

**Comment by dlimyy** [comment]
I have just tested it and it also only appears to work when CHECKSTYLE.OFF and CHECKSTYLE.ON are used instead of CODESTYLE.OFF and CODESTYLE.ON.

<img width="459" alt="image" src="https://user-images.githubusercontent.com/97420966/215248840-c31b52e6-d7b9-408d-a6e3-8f5567b71983.png">

I believe it is due to the value of offCommentFormat and onCommentFormat under SuppressionCommentFilter which is under checkstyle.xml being CHECKSTYLE.OFF and CHECKSTYLE.ON respectively.

We can fix it by either editing the guide or changing the value here to be CODESTYLE instead

**Comment by damithc** [comment]
Got it. Thanks for checking this @dlimyy 
I'll update the guide accordingly.
